# Generated by Django 6.1.1 on 2026-09-27 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_product_code"),
    ]

    def populate_codes(apps, schema_editor):
        Product = apps.get_model("core", "Product")

        for product in Product.objects.all():
            product.code = f"P{product.pk}"
            product.save()

    operations = [
        migrations.RunPython(populate_codes),
    ]
