# Generated by Django 6.1.1 on 2026-09-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_populate_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
