# Generated by Django 6.1.1 on 2026-09-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_make_product_code_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="quantity",
        ),
    ]
